# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Apt_Qns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apt_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=300)),
                ('qn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Apt_Qns')),
            ],
        ),
        migrations.AddField(
            model_name='apt_qns',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Apt_Test'),
        ),
        migrations.AddField(
            model_name='answers',
            name='qn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Apt_Qns'),
        ),
    ]
