# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_test',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='apt_test',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
